CC=gcc
CFLAGS=-Wall

all:	Lab01All Lab02All Lab09All Lab03All Lab04All Lab05All Lab06All Lab07All Lab08All Lab09All Lab10All Lab11All

Lab01All:	Lab01Set01Number01 Lab01Set01Number02 Lab01Set01Number03 Lab01Set02Number01 Lab01Set02Number02

Lab02All:	Lab02Set03Number01 Lab02Set03Number02 Lab02Set03Number03 Lab02Set03Number04 Lab02Set04Number01 Lab02Set04Number02 Lab02Set04Number03

Lab03All:	Lab03Set05Number01 Lab03Set05Number02 Lab03Set05Number03 Lab03Set05Number04 Lab03Set06Number01 Lab03Set06Number02

Lab04All:	Lab04Set07Number01 Lab04Set07Number02 Lab04Set07Number03

Lab05All:	Lab05Set08Number01 Lab05Set08Number02 Lab05Set08Number03

Lab06All: Lab06Set09Number01and02

Lab07All: Lab07Set10Number04 Lab07Set10Number05

Lab08All: Lab08Set11Number04

Lab09All: Lab09Number03Client Lab09Number03Server

Lab10All: Lab10Number01 Lab10Number02 Lab10Number03 Lab10Number04 Lab10Number05

Lab11All: Lab11Number01 Lab11Number02 Lab11Number03 Lab11Number04 Lab11Number05 Lab11Number06

Lab01Set01Number01:	Lab01Set01Number01.c
	${CC} ${CFLAGS2} Lab01Set01Number01.c -o Lab01Set01Number01

Lab01Set01Number02:	Lab01Set01Number02.c
	${CC} ${CFLAGS2} Lab01Set01Number02.c -o Lab01Set01Number02

Lab01Set01Number03:	Lab01Set01Number03.c
	${CC} ${CFLAGS2} Lab01Set01Number03.c -o Lab01Set01Number03

Lab01Set02Number01:	Lab01Set02Number01.c
	${CC} ${CFLAGS2} Lab01Set02Number01.c -o Lab01Set02Number01

Lab01Set02Number02:	Lab01Set02Number02.c
	${CC} ${CFLAGS2} Lab01Set02Number02.c -o Lab01Set02Number02

Lab02Set03Number01:	Lab02Set03Number01.c
	${CC} ${CFLAGS2} Lab02Set03Number01.c -o Lab02Set03Number01

Lab02Set03Number02:	Lab02Set03Number02.c
	${CC} ${CFLAGS2} Lab02Set03Number02.c -o Lab02Set03Number02

Lab02Set03Number03:	Lab02Set03Number03.c
	${CC} ${CFLAGS2} Lab02Set03Number03.c -o Lab02Set03Number03

Lab02Set03Number04:	Lab02Set03Number04.c
	${CC} ${CFLAGS2} Lab02Set03Number04.c -lm -o Lab02Set03Number04

Lab02Set04Number01:	Lab02Set04Number01.c
	${CC} ${CFLAGS2} Lab02Set04Number01.c -o Lab02Set04Number01

Lab02Set04Number02:	Lab02Set04Number02.c
	${CC} ${CFLAGS2} Lab02Set04Number02.c -o Lab02Set04Number02

Lab02Set04Number03:	Lab02Set04Number03.c
	${CC} ${CFLAGS2} Lab02Set04Number03.c -o Lab02Set04Number03

Lab03Set05Number01:	Lab03Set05Number01.c
	${CC} ${CFLAGS2} Lab03Set05Number01.c -o Lab03Set05Number01

Lab03Set05Number02:	Lab03Set05Number02.c
	${CC} ${CFLAGS2} Lab03Set05Number02.c -o Lab03Set05Number02

Lab03Set05Number03:	Lab03Set05Number03.c
	${CC} ${CFLAGS2} Lab03Set05Number03.c -o Lab03Set05Number03

Lab03Set05Number04:	Lab03Set05Number04.c
	${CC} ${CFLAGS2} Lab03Set05Number04.c -o Lab03Set05Number04

Lab03Set06Number01:	Lab03Set06Number01.c
	${CC} ${CFLAGS2} Lab03Set06Number01.c -o Lab03Set06Number01

Lab03Set06Number02:	Lab03Set06Number02.c
	${CC} ${CFLAGS2} Lab03Set06Number02.c -o Lab03Set06Number02

Lab04Set07Number01:	Lab04Set07Number01.c
	${CC} ${CFLAGS2} Lab04Set07Number01.c -o Lab04Set07Number01

Lab04Set07Number02:	Lab04Set07Number02.c
	${CC} ${CFLAGS2} Lab04Set07Number02.c -o Lab04Set07Number02

Lab04Set07Number03:	Lab04Set07Number03.c
	${CC} ${CFLAGS2} Lab04Set07Number03.c -o Lab04Set07Number03

Lab05Set08Number01:	Lab05Set08Number01.c
	${CC} ${CFLAGS2} Lab05Set08Number01.c -o Lab05Set08Number01

Lab05Set08Number02:	Lab05Set08Number02.c
	${CC} ${CFLAGS2} Lab05Set08Number02.c -o Lab05Set08Number02

Lab05Set08Number03:	Lab05Set08Number03.c
	${CC} ${CFLAGS2} Lab05Set08Number03.c -o Lab05Set08Number03

Lab06Set09Number01and02:	Lab06Set09Number01and02.c
	${CC} ${CFLAGS2} Lab06Set09Number01and02.c -o Lab06Set09Number01and02

Lab07Set10Number04:	Lab07Set10Number04.c
	${CC} ${CFLAGS2} Lab07Set10Number04.c -o Lab07Set10Number04

Lab07Set10Number05:	Lab07Set10Number05.c
	${CC} ${CFLAGS2} Lab07Set10Number05.c -o Lab07Set10Number05

Lab08Set11Number04:	Lab08Set11Number04.c
	${CC} ${CFLAGS2} Lab08Set11Number04.c -o Lab08Set11Number04

Lab09Number03Client:	Lab09Number03Client.c csapp.h csapp.c
	${CC} ${CFLAGS2} Lab09Number03Client.c csapp.c -o Lab09Number03Client

Lab09Number03Server:	Lab09Number03Server.c csapp.h csapp.c
	${CC} ${CFLAGS2} Lab09Number03Server.c csapp.c -o Lab09Number03Server

Lab10Number01:	Lab10Number01.c
	${CC} ${CFLAGS2} Lab10Number01.c -o Lab10Number01

Lab10Number02:	Lab10Number02.c
	${CC} ${CFLAGS2} Lab10Number02.c -o Lab10Number02

Lab10Number03:	Lab10Number03.c
	${CC} ${CFLAGS2} Lab10Number03.c -o Lab10Number03

Lab10Number04:	Lab10Number04.c
	${CC} ${CFLAGS2} Lab10Number04.c -o Lab10Number04

Lab10Number05:	Lab10Number05.c
	${CC} ${CFLAGS2} Lab10Number05.c -o Lab10Number05

Lab11Number01:	Lab11Number01.c
	${CC} ${CFLAGS2} Lab11Number01.c -o Lab11Number01

Lab11Number02:	Lab11Number02.c
	${CC} ${CFLAGS2} Lab11Number02.c -o Lab11Number02

Lab11Number03:	Lab11Number03.c
	${CC} ${CFLAGS2} Lab11Number03.c -o Lab11Number03

Lab11Number04:	Lab11Number04.c
	${CC} ${CFLAGS2} Lab11Number04.c -o Lab11Number04

Lab11Number05:	Lab11Number05.c
	${CC} ${CFLAGS2} Lab11Number05.c -o Lab11Number05

Lab11Number06:	Lab11Number06.c
	${CC} ${CFLAGS2} Lab11Number06.c -o Lab11Number06

clean:
	rm -f *.o *~ *.exe Lab01Set01Number01 Lab01Set01Number02 Lab01Set01Number03 Lab01Set02Number01 Lab01Set02Number02  Lab02Set03Number01 Lab02Set03Number02 Lab02Set03Number03 Lab02Set03Number04 Lab02Set04Number01 Lab02Set04Number02 Lab02Set04Number03 Lab03Set05Number01 Lab03Set05Number02 Lab03Set05Number03 Lab03Set05Number04 Lab03Set06Number01 Lab03Set06Number02 Lab04Set07Number01 Lab04Set07Number02 Lab04Set07Number03 Lab05Set08Number01 Lab05Set08Number02 Lab05Set08Number03 Lab06Set09Number01and02 Lab07Set10Number04 Lab07Set10Number05 Lab08Set11Number04 Lab09Number03Client Lab09Number03Server Lab10Number01 Lab10Number02 Lab10Number03 Lab10Number04 Lab10Number05 Lab11Number01 Lab11Number02 Lab11Number03 Lab11Number04 Lab11Number05 Lab11Number06 csapp.o